-- Supabase PostgreSQL schema for SmartMinibus.
-- Apply this to a new/empty Supabase project before running migrate_mysql_to_supabase.php.

CREATE TABLE public.users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    email varchar(150) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    role varchar(20) NOT NULL DEFAULT 'commuter' CHECK (role IN ('commuter', 'driver', 'admin')),
    phone varchar(20),
    profile_image varchar(255),
    status varchar(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    email_verified smallint NOT NULL DEFAULT 0 CHECK (email_verified IN (0, 1)),
    phone_verified smallint NOT NULL DEFAULT 0 CHECK (phone_verified IN (0, 1)),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.routes (
    route_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_name varchar(120) NOT NULL UNIQUE,
    origin varchar(120) NOT NULL,
    destination varchar(120) NOT NULL,
    distance_km numeric(8, 2),
    est_minutes integer,
    status varchar(20) NOT NULL DEFAULT 'active',
    origin_lat numeric(10, 7),
    origin_lng numeric(10, 7),
    dest_lat numeric(10, 7),
    dest_lng numeric(10, 7),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.route_stops (
    stop_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id bigint NOT NULL REFERENCES public.routes(route_id) ON DELETE CASCADE,
    stop_name varchar(120) NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    stop_sequence integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (route_id, stop_id)
);
CREATE INDEX route_stops_route_sequence_idx ON public.route_stops(route_id, stop_sequence);

CREATE TABLE public.minibuses (
    minibus_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number varchar(30) NOT NULL UNIQUE,
    plate_number varchar(20) NOT NULL UNIQUE,
    capacity integer NOT NULL DEFAULT 20,
    seat_status varchar(20) NOT NULL DEFAULT 'unknown' CHECK (seat_status IN ('unknown', 'available', 'full')),
    status varchar(20) NOT NULL DEFAULT 'active',
    driver_id bigint UNIQUE REFERENCES public.users(user_id) ON DELETE SET NULL,
    route_id bigint REFERENCES public.routes(route_id) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX minibuses_route_idx ON public.minibuses(route_id);

CREATE TABLE public.trips (
    trip_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    minibus_id bigint NOT NULL REFERENCES public.minibuses(minibus_id) ON DELETE CASCADE,
    route_id bigint NOT NULL REFERENCES public.routes(route_id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at timestamp without time zone,
    distance_km numeric(8, 2),
    avg_speed_kmh numeric(6, 2)
);
CREATE UNIQUE INDEX trips_one_active_driver_idx ON public.trips(driver_id) WHERE status = 'active';
CREATE UNIQUE INDEX trips_one_active_bus_idx ON public.trips(minibus_id) WHERE status = 'active';

CREATE TABLE public.driver_locations (
    location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    trip_id bigint REFERENCES public.trips(trip_id) ON DELETE SET NULL,
    minibus_id bigint REFERENCES public.minibuses(minibus_id) ON DELETE SET NULL,
    route_id bigint REFERENCES public.routes(route_id) ON DELETE SET NULL,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    accuracy numeric(10, 2),
    speed numeric(10, 2),
    heading numeric(10, 2),
    recorded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX driver_locations_driver_recorded_idx ON public.driver_locations(driver_id, recorded_at DESC);
CREATE INDEX driver_locations_bus_recorded_idx ON public.driver_locations(minibus_id, recorded_at DESC);

CREATE TABLE public.locations (
    location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    speed double precision,
    recorded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX locations_user_idx ON public.locations(user_id);

CREATE TABLE public.commuter_pickups (
    commuter_id bigint PRIMARY KEY REFERENCES public.users(user_id) ON DELETE CASCADE,
    route_id bigint NOT NULL REFERENCES public.routes(route_id) ON DELETE CASCADE,
    stop_id bigint NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pick_stop_route FOREIGN KEY (route_id, stop_id)
        REFERENCES public.route_stops(route_id, stop_id) ON DELETE CASCADE
);

CREATE TABLE public.schedules (
    schedule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id bigint NOT NULL REFERENCES public.routes(route_id) ON DELETE CASCADE,
    minibus_id bigint REFERENCES public.minibuses(minibus_id) ON DELETE SET NULL,
    departure_time time without time zone NOT NULL,
    days_of_week varchar(40) NOT NULL DEFAULT 'Mon-Sun',
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX schedules_route_idx ON public.schedules(route_id);
CREATE INDEX schedules_bus_idx ON public.schedules(minibus_id);

CREATE TABLE public.complaints (
    complaint_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    complaint_type varchar(30),
    route_id bigint REFERENCES public.routes(route_id) ON DELETE SET NULL,
    subject varchar(150) NOT NULL,
    message text NOT NULL,
    admin_response text,
    status varchar(20) NOT NULL DEFAULT 'Pending',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone
);
CREATE INDEX complaints_user_idx ON public.complaints(user_id);
CREATE INDEX complaints_route_idx ON public.complaints(route_id);
CREATE INDEX complaints_status_idx ON public.complaints(status);

CREATE TABLE public.notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(120) NOT NULL,
    message text NOT NULL,
    audience varchar(20) NOT NULL DEFAULT 'all',
    sent_by bigint REFERENCES public.users(user_id) ON DELETE SET NULL,
    recipient_id bigint REFERENCES public.users(user_id) ON DELETE CASCADE,
    route_id bigint REFERENCES public.routes(route_id) ON DELETE CASCADE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX notifications_audience_idx ON public.notifications(audience);
CREATE INDEX notifications_sender_idx ON public.notifications(sent_by);
CREATE INDEX notifications_recipient_idx ON public.notifications(recipient_id);
CREATE INDEX notifications_route_idx ON public.notifications(route_id);

CREATE TABLE public.notification_reads (
    notification_id bigint NOT NULL REFERENCES public.notifications(notification_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    read_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (notification_id, user_id)
);

CREATE TABLE public.verification_codes (
    verification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    email_code varchar(10),
    phone_code varchar(10),
    email_expires_at timestamp without time zone,
    phone_expires_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX verification_codes_user_idx ON public.verification_codes(user_id);

CREATE FUNCTION public.set_updated_at() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER commuter_pickups_set_updated_at
    BEFORE UPDATE ON public.commuter_pickups
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- The PHP app connects server-side as the database owner. Do not expose these
-- tables to Supabase's public Data API; there are intentionally no client RLS policies.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minibuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commuter_pickups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_codes ENABLE ROW LEVEL SECURITY;
